version: "3.8"
services:
  database:
    restart: always
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      command: --default-authentication-plugin=mysql_native_password


  url-shortener:
    build: .
    container_name: url-shortener
    links:
      - database
    depends_on:
      - database
    ports:
      - "8080:8080"

